Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"

  config.vm.provider "virtualbox" do |vb|
    vb.name = "centos7_vm"
    vb.memory = "4096"
    vb.cpus = 4
  end

  # Синхронизация локальной папки с Vagrant
  config.vm.synced_folder ".", "/vagrant"
end
